security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Usuario
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: login
                check_path: login
                username_parameter: email
                password_parameter: password
                success_handler: App\Security\LoginSuccessHandler
            logout:
                path: app_logout

    access_control:
    # tus reglas de acceso (descomentá las necesarias)
    # - { path: ^/disponibilidad, roles: ROLE_ADMIN }
    # - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    # - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    # - { path: ^/registro/nuevo, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    # - { path: ^/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    # - { path: ^/reservas, roles: ROLE_CLIENTE }
